import fs from 'node:fs';
import path from 'node:path';
const config=JSON.parse(fs.readFileSync('site-config.json','utf8'));
const origin=new URL(config.origin).origin;
const phone=config.phone;
const display=config.phoneDisplay;
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const cities=[
 {slug:'murmansk',name:'Мурманск',loc:'Мурманске',from:'Мурманска',region:'Мурманская область',districts:['Ленинский округ','Октябрьский округ','Первомайский округ'],title:'Поверка счётчиков воды в Мурманске без снятия — от 900 ₽ | ПРОМЕТР',desc:'Поверка счётчиков воды на дому в Мурманске: квартира — 1 000 ₽, частный дом — 1 200 ₽, от 4 приборов — 900 ₽ за каждый. Запись: 8 (950) 565-71-41.',intro:'Проверьте счётчики холодной и горячей воды у себя дома. Согласуем выезд по Мурманску, заранее рассчитаем стоимость и объясним, как найти результат в «Аршине».',localTitle:'Выезд по Мурманску — по вашему адресу',localText:'При записи сообщите округ, улицу и номер дома. Для квартиры уточните этаж, доступ к сантехническому шкафу и количество приборов. Время приезда согласуем заранее, с учётом адреса и вашего расписания.',localExtra:'Если нужна поверка в частном доме, расскажите, где установлен счётчик: внутри помещения или в отдельном узле ввода. Возможность работы без демонтажа зависит от модели и доступа к прибору.',question:'Как заказать поверку в Мурманске?',answer:'Позвоните по номеру 8 (950) 565-71-41, назовите адрес в Мурманске, тип жилья и число счётчиков. Специалист уточнит условия и согласует время выезда. Предварительная стоимость для квартиры — 1 000 ₽ за прибор.'},
 {slug:'simferopol',name:'Симферополь',loc:'Симферополе',from:'Симферополя',region:'Крым',districts:['Железнодорожный район','Киевский район','Центральный район'],title:'Поверка счётчиков воды в Симферополе на дому — цены | ПРОМЕТР',desc:'Поверка водосчётчиков в Симферополе без снятия. 1 000 ₽ в квартире, 1 200 ₽ в частном доме; от 4 счётчиков — по 900 ₽. ПРОМЕТР: 8 (950) 565-71-41.',intro:'Счётчик остаётся на месте — специалист проводит измерения у вас дома. Поверка квартирных приборов и счётчиков в частных домах Симферополя по согласованной цене.',localTitle:'Для квартир и частных домов Симферополя',localText:'При оформлении заказа назовите улицу и район Симферополя. Если прибор находится в частном доме, заранее опишите место установки и доступ к воде. Это поможет согласовать выезд и проверить, подходит ли поверка без снятия.',localExtra:'Есть несколько приборов с подходящим сроком поверки? Сообщите об этом при записи: при заказе от четырёх счётчиков действует тариф 900 ₽ за каждый. Условия общего выезда уточним до оформления заказа.',question:'Сколько стоит поверка в частном доме в Симферополе?',answer:'Тариф для частного дома — 1 200 ₽ за один счётчик. При записи сообщите адрес, модель прибора и место установки. Итоговую стоимость и возможность поверки на месте согласуем до приезда.'},
 {slug:'sevastopol',name:'Севастополь',loc:'Севастополе',from:'Севастополя',region:'Севастополь',districts:['Гагаринский район','Ленинский район','Нахимовский район','Балаклавский район'],title:'Поверка счётчиков воды в Севастополе — на дому без снятия | ПРОМЕТР',desc:'Закажите поверку счётчиков воды в Севастополе: 1 000 ₽ за прибор в квартире, 1 200 ₽ в доме, от 4 приборов — по 900 ₽. Телефон: 8 (950) 565-71-41.',intro:'Подходит срок поверки? Согласуйте визит специалиста в Севастополе. Проверим прибор на месте, если это допускает его методика, и оформим результаты поверки.',localTitle:'Запись на выезд по Севастополю',localText:'Чтобы подобрать время приезда, сообщите точный адрес и район Севастополя. Для адресов в Балаклаве и на удалении от центра отдельно согласуем маршрут. Доступность выезда на конкретную дату уточняется по телефону.',localExtra:'В квартире с несколькими водомерами подготовьте сведения по каждому прибору: модель, заводской номер и дату предыдущей поверки. Горячую и холодную воду можно проверить за один согласованный визит.',question:'Можно ли вызвать специалиста в Балаклаву?',answer:'Назовите точный адрес в Балаклавском районе по телефону 8 (950) 565-71-41. Специалист проверит возможность выезда, согласует дату и окончательную стоимость. Доступное время зависит от маршрута специалиста.'}
];
const general={slug:'',name:'Все города',loc:'',title:'Поверка счётчиков воды на дому — цены от 900 ₽ | ПРОМЕТР',desc:'ПРОМЕТР: поверка счётчиков воды в Мурманске, Симферополе и Севастополе. 1 000 ₽ в квартире, 1 200 ₽ в частном доме, от 4 приборов — по 900 ₽.',intro:'Специалист приедет к вам домой и проверит счётчик без снятия. Понятная стоимость, согласованное время и результаты поверки в ФГИС «Аршин».',localTitle:'Одна служба. Три города.',localText:'Работаем с заявками на поверку в Мурманске, Симферополе и Севастополе. У каждого города — своя страница с условиями выезда и ответами на вопросы. Записаться можно по единому телефону.',localExtra:'Сообщите город, адрес, тип жилья и количество приборов. Мы уточним возможность поверки на месте и согласуем стоимость до визита.',question:'В каких городах можно заказать поверку?',answer:'Принимаем заявки из Мурманска, Симферополя и Севастополя. Позвоните по номеру 8 (950) 565-71-41 и назовите точный адрес. Дату и условия выезда согласуем при записи.'};
const money=n=>new Intl.NumberFormat('ru-RU').format(n);
const route=c=>c.slug?`/${c.slug}/`:'/';
const arrow='<span aria-hidden="true">↗</span>';
const check='<span class="check" aria-hidden="true">✓</span>';
const call=(label,cls='button')=>`<a class="${cls}" href="tel:${phone}" data-track="call">${label} ${arrow}</a>`;
const cityLinks=(current)=>cities.map(c=>`<a href="${current.slug?'../':'./'}${c.slug}/"${current.slug===c.slug?' aria-current="page"':''}>${c.name} ${arrow}</a>`).join('');
const favicon=encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="8" fill="#122f40"/><path d="M8 23V9h16v14h-5V13h-6v10Z" fill="#8be1cd"/></svg>');
function render(c){
 const base=c.slug?'../':'./';
 const url=origin+route(c);
 const area=c.slug?`в ${c.loc}`:'на дому';
 const h1=`Поверка счётчиков воды ${area}`;
 const faqs=[
  [c.question,c.answer],
  [`Сколько стоит поверка счётчика${c.slug?' в '+c.loc:''}?`,'В квартире — 1 000 ₽ за прибор, в частном доме — 1 200 ₽. При заказе от четырёх счётчиков — 900 ₽ за каждый. До выезда согласуйте адрес, число приборов и условия применения тарифа.'],
  ['Нужно ли снимать счётчик?','Поверка на месте возможна, если её допускает методика поверки конкретной модели и есть доступ к прибору и точке подключения. При записи назовите модель: специалист уточнит, можно ли выполнить работу без демонтажа.'],
  ['Как узнать, когда нужна следующая поверка?','Проверьте сведения о предыдущей поверке в ФГИС «Аршин» и документацию прибора. Межповерочный интервал зависит от типа счётчика: универсального срока для всех моделей горячей или холодной воды нет.'],
  ['Что подготовить к приезду специалиста?','Освободите доступ к счётчикам и смесителю, подготовьте паспорта приборов, если они сохранились. Для работы требуется подача воды. Если счётчик расположен в труднодоступном месте, предупредите об этом при записи.'],
  ['Где проверить результат поверки?','Сведения ищут в открытой базе ФГИС «Аршин» по заводскому номеру счётчика. Уточните у исполнителя срок передачи данных. После появления записи сравните номер прибора, дату поверки и результат.'],
  ['Если прибор не прошёл поверку, что дальше?','Специалист сообщит результат и объяснит дальнейшие действия. Для непригодного прибора может потребоваться ремонт или замена. Порядок оплаты при отрицательном результате уточните до заказа — замена не включена в тариф поверки.']
 ];
 const offers=[['Поверка в квартире',1000],['Поверка в частном доме',1200],['Поверка от 4 счётчиков — за один прибор',900]].map(([name,price])=>({'@type':'Offer',name,price,priceCurrency:'RUB',url:url+'#prices',description:name+'; стоимость за один счётчик; условия выезда согласуются при записи.'}));
 const graph=[
 {'@type':'Organization','@id':origin+'/#organization',name:config.organization,url:origin+'/',telephone:phone,taxID:config.inn,identifier:{'@type':'PropertyValue',propertyID:'Номер аккредитации',value:config.accreditation},areaServed:cities.map(x=>({'@type':'City',name:x.name}))},
 {'@type':'WebSite','@id':origin+'/#website',url:origin+'/',name:'ПРОМЕТР — поверка счётчиков воды',inLanguage:'ru-RU',publisher:{'@id':origin+'/#organization'}},
 {'@type':'WebPage','@id':url+'#webpage',url,name:c.title,description:c.desc,inLanguage:'ru-RU',isPartOf:{'@id':origin+'/#website'},mainEntity:{'@id':url+'#service'}},
 {'@type':'Service','@id':url+'#service',name:h1,serviceType:'Поверка счётчиков холодной и горячей воды',provider:{'@id':origin+'/#organization'},areaServed:(c.slug?[c]:cities).map(x=>({'@type':'City',name:x.name})),hasOfferCatalog:{'@type':'OfferCatalog',name:'Стоимость поверки',itemListElement:offers}},
 {'@type':'FAQPage','@id':url+'#faq',mainEntity:faqs.map(([name,text])=>({'@type':'Question',name,acceptedAnswer:{'@type':'Answer',text}}))},
 ...(c.slug?[{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Главная',item:origin+'/'},{'@type':'ListItem',position:2,name:'Поверка в '+c.loc,item:url}]}]:[])
 ];
 return `<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(c.title)}</title><meta name="description" content="${esc(c.desc)}"><meta name="robots" content="index,follow,max-image-preview:large"><meta name="theme-color" content="#122f40"><link rel="canonical" href="${url}"><meta property="og:type" content="website"><meta property="og:locale" content="ru_RU"><meta property="og:site_name" content="ПРОМЕТР"><meta property="og:title" content="${esc(c.title)}"><meta property="og:description" content="${esc(c.desc)}"><meta property="og:url" content="${url}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(c.title)}"><meta name="twitter:description" content="${esc(c.desc)}"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,${favicon}"><link rel="stylesheet" href="${base}assets/layout.css"><script defer src="${base}assets/site.js"></script><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph}).replaceAll('<','\\u003c')}</script></head>
<body><a href="#main" class="skip-link">Перейти к содержимому</a>
<div class="topline"><div class="wrap top-inner"><span>Служба поверки счётчиков воды</span><span>${c.slug?c.name:'Мурманск · Симферополь · Севастополь'}</span></div></div>
<header class="header wrap"><a class="brand" href="${base}" aria-label="ПРОМЕТР — главная"><span class="brand-symbol" aria-hidden="true">П</span><span>ПРОМЕТР<small>Точность в каждом измерении</small></span></a><nav aria-label="Основная навигация"><a href="#prices">Цены</a><a href="#process">Как проходит</a><a href="#documents">Документы</a><a href="#contacts">Контакты</a></nav><a class="phone" href="tel:${phone}" data-track="call">${display}<small>Запись по телефону</small></a></header>
<main id="main"><div class="wrap">${c.slug?`<nav class="breadcrumbs" aria-label="Хлебные крошки"><a href="../">Главная</a><span aria-hidden="true">/</span><span>Поверка в ${c.loc}</span></nav>`:''}
<section class="hero"><div><p class="eyebrow">ПОВЕРКА БЕЗ СНЯТИЯ · ${c.slug?c.name.toUpperCase():'ВЫЕЗД НА ДОМ'}</p><h1>Поверка счётчиков воды <em>${area}.</em></h1><p class="lead">${c.intro}</p><div class="hero-actions">${call('Записаться на поверку')}<a class="text-link" href="#prices">Рассчитать стоимость <span aria-hidden="true">↓</span></a></div><div class="hero-proof">${check}<span>ООО «ПРОМЕТР» · Аттестат ${config.accreditation}</span></div></div>
<div class="hero-visual"><img class="hero-photo" src="${base}assets/water-meters-hero.webp" width="1200" height="800" alt="Счётчики горячей и холодной воды на трубах — иллюстрация" fetchpriority="high"><aside class="price-panel" aria-label="Тарифы на поверку"><div class="panel-head"><span>СТОИМОСТЬ В КВАРТИРЕ</span><span class="panel-label">₽ / прибор</span></div><div class="huge">1 000 <small>₽</small></div><p class="price-caption">Один счётчик. Понятная цена.</p><hr><div class="price-line"><span>В частном доме</span><strong>1 200 ₽</strong></div><div class="price-line"><span>От 4 счётчиков</span><strong>900 ₽ / шт.</strong></div><a class="panel-cta" href="#prices">Посчитать мой заказ <span aria-hidden="true">↗</span></a><p class="panel-note">Адрес, условия и стоимость согласуем до выезда.</p></aside></div></section><div class="quick-call"><div><h2>Запишитесь на удобное время</h2><p>Сообщите адрес и количество приборов — уточним детали выезда.</p></div><a class="phone" href="tel:${phone}" data-track="call">${display}</a></div>
<div class="benefit-strip"><div>${check}<span><strong>Без демонтажа</strong><small>Если это допускает методика прибора</small></span></div><div>${check}<span><strong>Результат в «Аршине»</strong><small>Можно проверить по номеру счётчика</small></span></div><div>${check}<span><strong>Удобное время</strong><small>Дату приезда согласуем с вами</small></span></div></div></div>
<section class="section wrap" id="services"><div class="section-heading"><div><p class="eyebrow">01 / ВАРИАНТЫ УСЛУГИ</p><h2>Для одного счётчика.<br>И для всего дома.</h2></div><p>Поверка холодной и горячей воды${c.slug?' в '+c.loc:''}. Тариф указан за один прибор.</p></div><div class="tariffs"><article class="tariff"><span class="number">01</span><h3>В квартире</h3><p>Для счётчиков холодной<br>и горячей воды</p><div class="tariff-price">1 000 ₽ <small>/ шт.</small></div></article><article class="tariff"><span class="number">02</span><h3>В частном доме</h3><p>С учётом доступности прибора<br>и возможности поверки на месте</p><div class="tariff-price">1 200 ₽ <small>/ шт.</small></div></article><article class="tariff featured"><span class="number">03</span><span class="offer-label">ВЫГОДНЕЕ ВМЕСТЕ</span><h3>От 4 счётчиков</h3><p>Специальная цена при заказе<br>четырёх и более приборов</p><div class="tariff-price">900 ₽ <small>/ шт.</small></div></article></div>
<div class="included"><strong>В услугу входят</strong><span>${check}Выезд по согласованному адресу</span><span>${check}Поверка прибора</span><span>${check}Оформление результатов</span></div></section>
<section class="when-section"><div class="wrap section when-grid"><div><p class="eyebrow">02 / КОГДА ПОРА НА ПОВЕРКУ</p><h2>Проверьте дату.<br>Сохраните свой счётчик.</h2><p class="lead">Подходит срок поверки? Это повод проверить точность прибора, а не сразу покупать новый.</p><ul class="reasons"><li>${check}<div><strong>Заканчивается срок поверки</strong><p>Сверьте дату в документах прибора и сведения о предыдущей поверке в «Аршине».</p></div></li><li>${check}<div><strong>Нужно подтвердить точность</strong><p>Поверка покажет, соответствует ли прибор метрологическим требованиям.</p></div></li><li>${check}<div><strong>Счётчик исправен</strong><p>Если он проходит поверку, его можно использовать дальше в пределах установленного срока.</p></div></li><li>${check}<div><strong>Удобнее принять специалиста дома</strong><p>Работа на месте возможна, если это допускает методика и есть доступ к прибору.</p></div></li></ul></div><figure><img src="${base}assets/technician-measurement.webp" width="1200" height="800" alt="Подготовка измерительного оборудования рядом с водосчётчиком — иллюстрация" loading="lazy" decoding="async"><figcaption>Иллюстрация поверки на дому. Конкретное оборудование зависит от методики вашего прибора.</figcaption></figure></div></section>
<section class="process-section" id="process"><div class="wrap section"><div class="section-heading"><div><p class="eyebrow">03 / ПОРЯДОК РАБОТЫ</p><h2>От записи до результата.<br>Четыре простых шага.</h2></div><p>Счётчик не нужно везти в лабораторию, если его методика допускает поверку на месте.</p></div><ol class="steps"><li><span>1</span><h3>Ваш звонок</h3><p>Назовите город, адрес, тип жилья и количество счётчиков, которым нужна поверка.</p></li><li><span>2</span><h3>Согласование</h3><p>Уточним модель прибора, доступ к нему, цену и удобную дату приезда.</p></li><li><span>3</span><h3>Проверим на месте</h3><p>Подготовьте доступ к счётчикам и воде. Специалист проведёт измерения и сообщит результат.</p></li><li><span>4</span><h3>Оформим результат</h3><p>Сведения о поверке передаются в ФГИС «Аршин». Срок передачи и необходимые вам документы уточните у специалиста.</p></li></ol><div class="prepare"><strong>Перед приездом</strong><p>Освободите доступ к прибору и смесителю. Подготовьте паспорт счётчика, если он сохранился, и предупредите, если есть сложности с подачей воды.</p></div></div></section>
<section class="pricing-section" id="prices"><div class="wrap section"><div class="section-heading"><div><p class="eyebrow">04 / ЦЕНЫ НА ПОВЕРКУ</p><h2>Рассчитайте стоимость<br>до звонка.</h2></div><p>Тарифы на поверку ${c.slug?'в '+c.loc:'на дому'}. Цена за один прибор, без ремонта и замены.</p></div><table class="price-table"><thead><tr><th scope="col">Услуга</th><th scope="col">За счётчик</th></tr></thead><tbody><tr><td>В квартире</td><td>1 000 ₽</td></tr><tr><td>В частном доме</td><td>1 200 ₽</td></tr><tr><td>От четырёх приборов</td><td>900 ₽</td></tr></tbody></table><div class="calculator" data-calculator><div><h3>Сколько будет стоить поверка?</h3><p>Выберите тип жилья и количество приборов.</p></div><div class="calc-fields"><label for="property">Тип жилья<select id="property" name="property"><option value="apartment">Квартира</option><option value="house">Частный дом</option></select></label><label for="quantity">Счётчиков<input id="quantity" name="quantity" type="number" min="1" max="100" step="1" value="2" inputmode="numeric"></label></div><div class="calc-result" aria-live="polite" aria-atomic="true"><span>Предварительно</span><output id="total" for="property quantity">2 000 ₽</output><small id="calculation">2 × 1 000 ₽</small></div><p class="calc-error" id="calc-error" role="alert" hidden>Укажите целое количество от 1 до 100.</p><p class="calc-disclaimer">Расчёт по указанным тарифам. Условия заказа от четырёх приборов и окончательную стоимость подтвердим по телефону. Замена и ремонт счётчиков в расчёт не входят.</p><noscript><p>Стоимость двух приборов в квартире — 2 000 ₽. Для другого расчёта позвоните: ${display}.</p></noscript></div>
</div></section>
<section class="section wrap documents" id="documents"><div><p class="eyebrow">05 / ДОКУМЕНТЫ И ПРОВЕРКА</p><h2>Доверие начинается<br>с конкретных данных.</h2><p class="lead">${config.organization}<br>ИНН ${config.inn}</p><dl class="document-data"><div><dt>Номер аккредитации</dt><dd>${config.accreditation}</dd></div><div><dt>Дата записи по аттестату</dt><dd>25 мая 2023 года</dd></div></dl><p>Юридический адрес по аттестату: 420141, г. Казань, ул. Академика Завойского, д. 23, помещ. 1003. Это адрес организации, а не пункт приёма в вашем городе.</p><p>Откройте аттестат и проверьте актуальные сведения в реестре Росаккредитации по номеру записи. Статус и область аккредитации следует проверять на дату заказа.</p><a class="text-link" href="https://pub.fsa.gov.ru/ral" target="_blank" rel="noopener noreferrer">Реестр Росаккредитации ${arrow}</a><div class="arshin"><strong>Как найти свою поверку в «Аршине»</strong><p>Откройте реестр результатов поверки, укажите заводской номер счётчика и проверьте модель, дату и результат. Номер можно найти на корпусе или в паспорте прибора.</p><a href="https://fgis.gost.ru/fundmetrology/cm/results" target="_blank" rel="noopener noreferrer" class="text-link">Перейти в ФГИС «Аршин» ${arrow}</a></div></div><figure class="certificate"><a href="${base}assets/accreditation.jpg" target="_blank" rel="noopener"><img src="${base}assets/accreditation.jpg" width="1290" height="901" alt="Аттестат аккредитации ООО ПРОМЕТР RA.RU.314482, ИНН 1686024950" loading="lazy" decoding="async"></a><figcaption><span>Аттестат ООО «ПРОМЕТР»</span><a href="${base}assets/accreditation.jpg" target="_blank" rel="noopener">Открыть ${arrow}</a></figcaption><p>Копия предоставленного документа. Дата формирования выписки — 8 июня 2023 года.</p></figure></section>
<section class="local-section"><div class="wrap section"><div class="local-grid"><div><p class="eyebrow">06 / РЯДОМ С ВАМИ</p><h2>${c.localTitle}</h2></div><div><p>${c.localText}</p><p>${c.localExtra}</p>${c.districts?`<ul class="districts" aria-label="Районы города">${c.districts.map(d=>`<li>${d}</li>`).join('')}</ul><p class="subtle">Точный адрес и возможность выезда подтвердим при записи.</p>`:''}</div></div><nav class="city-links" aria-label="Поверка в городах">${cityLinks(c)}</nav></div></section>
<section class="faq-section" id="faq"><div class="wrap section faq-grid"><div><p class="eyebrow">07 / ОТВЕТЫ НА ВОПРОСЫ</p><h2>Всё, что стоит<br>знать до звонка.</h2><p>Остались вопросы по вашему счётчику?</p><a class="phone" href="tel:${phone}" data-track="call">${display}</a></div><div class="faq-list">${faqs.map(([q,a],i)=>`<details${i===0?' open':''}><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></div></section>
<section class="section wrap" id="contacts"><div class="contact-panel"><div><p class="eyebrow">ЗАПИСЬ НА ПОВЕРКУ${c.slug?' · '+c.name.toUpperCase():''}</p><h2>Согласуем время.<br>Остальное — наша работа.</h2><p>Назовите город, адрес и количество счётчиков.<br>Стоимость подтвердим до выезда.</p></div><div class="contact-action"><a class="contact-phone" href="tel:${phone}" data-track="call">${display}</a>${call('Позвонить и записаться','button light')}<p>Единый номер для трёх городов</p></div></div></section></main>
<footer class="wrap footer"><div><a class="brand" href="${base}">ПРОМЕТР</a><p>${config.organization} · ИНН ${config.inn}<br>Аттестат ${config.accreditation}</p></div><nav aria-label="Города в подвале">${cityLinks(c)}</nav><div><a href="tel:${phone}" class="phone" data-track="call">${display}</a><p>Приём заявок по телефону.<br>Выезд по предварительной записи.</p></div><p class="footer-note">Поверка счётчиков холодной и горячей воды. Стоимость указана за один прибор. Условия заказа и возможность поверки без снятия уточняйте при записи.</p></footer><div class="mobile-call"><span>Поверка от 900 ₽<small>при заказе от 4 приборов</small></span>${call('Позвонить')}</div></body></html>`;
}
for(const c of [general,...cities]) { const dir=path.join('dist',c.slug);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),render(c)); }
fs.writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\n\nSitemap: ${origin}/sitemap.xml\n`);
fs.writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${[general,...cities].map(c=>`  <url><loc>${origin}${route(c)}</loc></url>`).join('\n')}\n</urlset>\n`);
fs.writeFileSync('dist/404.html',`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>Страница не найдена — ПРОМЕТР</title><style>body{font:18px/1.6 Arial;margin:12vh auto;padding:24px;max-width:640px;color:#122f40}a{color:#087d77}h1{font-size:42px}</style></head><body><p>ПРОМЕТР · 404</p><h1>Такой страницы нет</h1><p>Перейдите на главную или откройте страницу вашего города.</p><p><a href="/">Главная</a> · <a href="/murmansk/">Мурманск</a> · <a href="/simferopol/">Симферополь</a> · <a href="/sevastopol/">Севастополь</a></p><p><a href="tel:${phone}">${display}</a></p></body></html>`);
fs.writeFileSync('dist/.nojekyll','');
console.log('Created 4 complete static pages, 404, sitemap and robots for '+origin);
